### ISSUE TITLE
Suggestions on early quests and rewards

### ISSUE THREAD

**Issue by RogueFanUK** [prolog/shadow-of-the-wyrm#20]
Just a couple of thoughts. I had to trial & error what the rewards are for the early Isen Dun quests are, perhaps we could make it clearer in both the dialogue and the quest summaries

Blacksmith - add another line of dialogue - "Bring me the gem and I will make you a mighty weapon!", add "and he will forge a mighty weapon for you" to the quest summary.
Ploughman - add another line of dialogue -"Bring me the gem and I will provide you with sustenance for your travels!", add "and he will reward you with food" to the quest summary.
Wizard - add a literacy check, then either add "Bring me the gem and I will teach you the art of reading! or "Bring me the gem and I will give you scrolls to help you on your journey", add "and he will teach you to read" or "and he will reward you with scrolls" to the quest summary.

Also, consider making the second wizard quest (for the magic shard) reward the ability to read if not already literate, so a warrior doesn't have to give up the magic hammer if they want to read scrolls, or the existing wandcraft if literate.

Thanks for reading.

**Comment by prolog** [comment]
Hi. These don't quite fit the tone of the writing I'm going for, and I'm not going to rebalance the initial Isen Dun quests to allow both literacy and the artifact hammer. If playing a character that wants the hammer, there is another way to achieve literacy elsewhere in the game. Thank you for offering these suggestions.
