### ISSUE TITLE
Download link on website is incorrect

### ISSUE THREAD

**Issue by RedPine91** [prolog/shadow-of-the-wyrm#26]
The "Windows 7+" download on the main website, "https://www.shadowofthewyrm.org/downloads.html", downloads the spritesheets instead of the main game.

The link below it, "Spritesheets", also downloads spritesheets.

It looks like you accidentally copy/pasted the wrong files with your latest official update.

**Comment by prolog** [comment]
It was a CSS issue - the border of the line below took up too much space and bled into the first link. You could still download the game, but had to be at the top of the first link. This should be fixed now. Thanks so much for reporting this.
