### ISSUE TITLE
Improve Linux packaging capability

### ISSUE THREAD

**Issue by tranzystorek-io** [prolog/shadow-of-the-wyrm#33]
I recently tried to package this for Void Linux, but met a few roadbumps that could be addressed:

- Recent releases aren't tagged in this repo or offered as source downloads on homepage
- Could use an automatic install step (possibly consider a switch to CMake?)
- If I understand correctly, the game executable needs to be placed and run from the same directory where the assets are stored, it would be convenient if the game used an environment variable to determine the asset dir at runtime.

Hope the above doesn't sound aggressive or accusatory, personally I find this project really cool and would love to see it flourish in various distros etc. 😄

**Comment by prolog** [comment]
All good!

- master will always build the latest release. There are tags for each version but I forgot git doesn't push these by default, so I did a git push --tags and they should all be present in the repo now.
- I can add a suggestion to switch to cmake for the automatic install step; I don't know if or when I'll get to this. I've always enjoyed premake's simplicity. In the meantime: Larzid has maintained Arch builds for SotW for years: perhaps his install steps might help? see eg: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sotwhttps://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sotw
- I've allowed overriding various directories in swyrm.ini in the past (you can see a few examples in there). assets (such as spritesheets) as well as other directories such as data (for maps) aren't overridable this way, but I will make a note to add this in future

**Comment by tranzystorek-io** [comment]
Thank you for taking the time to respond! Some additional notes:

- Install step is convenient but as you pointed out, distros can generally handle that manually like arch does, void included
- For context how configuring the dirs could work: either swyrm.ini gets a field for pointing to the root game directory, like /usr/share/shadow-of-the-wyrm/ that holds all dirs like assets, data etc, or reads it from an env variable e.g. SOTW_ROOT_DIR and then distros provide a wrapper script that sets it before running the game

**Comment by prolog** [comment]
Thanks - updated my notes (suggestions.txt) with your second point.
